name: HelloWorld Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      # 配置JDK环境
      - name: 配置JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # 编译Java代码（构建环节）
      - name: 编译代码
        run: javac Hello.java

      # 运行程序（测试环节）
      - name: 运行程序
        run: java Hello
